language: bash

services:
- docker


script:
- docker build -t pengdevs/ktor-sample -t pengdevs/ktor-sample:$TRAVIS_BUILD_NUMBER .

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push pengdevs/ktor-sample:$TRAVIS_BUILD_NUMBER
- docker push pengdevs/ktor-sample
